# network
WIFI_SSID = "dummy"
WIFI_PWD = "dummy"

# hub
CONTROLLER_HOST = "home-hub.local"
CONTROLLER_PORT = 5000

# pico
PICO_PORT = 80
IDEAL_DURATION = 5
TIMEOUT_TIME = 30

# relay
PUMP_RELAY_CTRL_PIN = 16
SENSOR_RELAY_CTRL_PIN = 0
RELAY_OFF = 1
RELAY_ON = 0

# sensor
CALIBRATION_MIN = 14467
CALIBRATION_MAX = 65535
ADC_PIN = 26
RELAY_DELAY = 0.1
